# This is a template for the secrets.toml file
# Copy this file to .streamlit/secrets.toml and add your API keys

[perplexity]
api_key = "your-perplexity-api-key-here"

# [openai]
# api_key = "your-openai-api-key-here"
